#!/bin/bash -e

# Do we want to modify the config first with the script?
[ -f /etc/service/postfix/run.config ] && source /etc/service/postfix/run.config

if [ "$MAILNAME" ]; then
  echo "$MAILNAME" > /etc/mailname

  #Configure postfix
  postconf -e 'smtpd_tls_auth_only = no'
  postconf -e 'smtp_use_tls = yes'
  postconf -e 'smtpd_use_tls = yes'
  postconf -e 'smtp_tls_note_starttls_offer = yes'
  postconf -e "smtpd_tls_key_file = /etc/letsencrypt/${MAILNAME}/privkey.pem"
  postconf -e "smtpd_tls_cert_file = /etc/letsencrypt/${MAILNAME}/fullchain.pem"
  postconf -e 'smtpd_tls_loglevel = 1'
  postconf -e 'smtpd_tls_received_header = yes'
  postconf -e 'smtpd_tls_session_cache_timeout = 3600s'
  postconf -e 'tls_random_source = dev:/dev/urandom'
  postconf -e myhostname="$MAILNAME"

fi

if [ "$MY_NETWORKS" ]; then
  postconf -e mynetworks="$MY_NETWORKS"
fi

if [ "$MY_DESTINATION" ]; then
  postconf -e mydestination="$MY_DESTINATION"
fi

if [ "$ROOT_ALIAS" ]; then
  sed -i '/^root:/d' /etc/aliases
  echo "root: $ROOT_ALIAS" >> /etc/aliases
  newaliases
fi

if [ "$RELAY_HOST" ]; then
  RELAY="[$RELAY_HOST]"
  
  if [ "$PORT" ]; then
    RELAY="${RELAY}:$PORT"
  fi

  if [ "$USERNAME" ] && [ "$PASSWORD" ]; then
    RELAY="${RELAY} ${USERNAME}:${PASSWORD}" > /etc/postfix/sasl_passwd    
  fi  
  
  echo "$RELAY" > /etc/postfix/sasl_passwd
  postmap /etc/postfix/sasl_passwd
  chmod 0600 /etc/postfix/sasl_passwd /etc/postfix/sasl_passwd.db
  if [ "$PORT" ]; then
    postconf -e relayhost="[$RELAY_HOST]:${PORT}"
  else
    postconf -e relayhost="[$RELAY_HOST]"
  fi

fi

# We have to start and stop postfix first through init.d to populate
# postfix spool directory for chroot in which postfix is running.
# We do it a bit differently in alpine as the init.d scripts use
# openrc-run which is not supported by alpine very well, as the 
# use on init systems is discouraged in general
if [ -f /etc/alpine-release ]; then
  /usr/sbin/postfix -c /etc/postfix start >/dev/null 2>&1
  /usr/sbin/postfix -c /etc/postfix abort >/dev/null 2>&1
else
  /etc/init.d/postfix start
  /etc/init.d/postfix abort
fi

# Is there any other script to run here?
[ -f /etc/service/postfix/run.initialization ] && source /etc/service/postfix/run.initialization

exec /usr/lib/postfix/sbin/master -c /etc/postfix -d 2>&1
